```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WVPlots)
library(clue)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(cowplot)
theme_set(theme_cowplot())
library(corrplot)
library(visreg)
library(ggcorrplot)
library(ggseg3d)
library(ggseg)
library(ggsegSchaefer)
library(psych)
library(nlme)
library(zoo)
library(mgcv)
library(gratia)
k=3
```

```{r setup, include=FALSE}
n <- 1
colfunc <- colorRampPalette(c("yellow","purple"))(400)
age_H_sorted <- read.csv('../Derivatives/BCP_thalamus.csv')
col <- "lhVLp"
allcol <- data.frame(rowMeans(age_H_sorted[col]))
colnames(allcol) <- 'age'
allcol$age <- scale(allcol$age)
allcol$age_scan <- age_H_sorted[['scan_age']]
allcol$sex <- age_H_sorted[['sex']]
allcol$motion <- age_H_sorted[['mFD']]
allcol$fsid <- as.factor(age_H_sorted[['sub_id']])
allcol <- allcol %>% drop_na('age')
lm_resid <- residuals(gam(age ~ sex + motion + s(fsid, bs = "re"), data = allcol))
allcol$age_resid <- lm_resid
avg_values <- allcol %>%
    group_by(age_scan) %>%
    summarise(mean_age = mean(age_resid, na.rm = TRUE))
model <- gam(allcol[['age_resid']] ~ s(age_scan, k=k), data = allcol)
derv <- derivatives(model, unconditional = F) #interval = "simultaneous", 
increasing.range <- derv[['age_scan']][derv[['.lower_ci']] > 0][derv[['.upper_ci']] > 0]
decreasing.range <- derv[['age_scan']][derv[['.lower_ci']] < 0][derv[['.upper_ci']] < 0]
print(c(max(increasing.range, na.rm=TRUE), min(decreasing.range, na.rm=TRUE)))
print(summary(model))
pred <- predict(model, se.fit=T)
allcol$prediction <- pred$fit
allcol$ymin <- pred$fit-1.96*pred$se.fit
allcol$ymax <- pred$fit+1.96*pred$se.fit
p <- ggplot(data = allcol, mapping = aes(x = age_scan, y = age_resid)) +
    geom_point(size = 2, alpha = 1) +
    geom_line(aes(group = fsid), color = colfunc[n]) +geom_point(color = colfunc[n], size = 2) + 
    geom_vline(xintercept = max(increasing.range, na.rm=TRUE), color = 'red', linetype = "dashed") + ylim(-3,3)+
    geom_vline(xintercept = min(decreasing.range, na.rm=TRUE), color = 'blue', linetype = "dashed")
ggsave(paste0(col, 'thalamus_scatter_BCP.eps'), plot=p, width=6, height=4, units='in', dpi=300)
p <- ggplot(data = allcol, mapping = aes(x = age_scan, y = prediction),color=colfunc[n]) + ylim(-3,3)+
geom_smooth(method="gam", formula= y~s(x, k=k), se=TRUE, alpha=1,color=colfunc[n], level=0.999) 
ggsave(paste0(col, 'thalamus_mean_BCP.eps'), plot=p, width=6, height=4, units='in', dpi=300)
```